
from visualisation import *
from solar_analysis import *
from weather_analysis import *
from economic import *
from data_loader import *
df = pd.read_csv('solar_energy_data_fixed(1).csv')
df["Date"] = pd.to_datetime(df["Date"])

print("===================================================================================")
print("                              QUESTIONS AND ANSWERS                                ")
print("===================================================================================")

#Q1
print("\nQ1= how much electricity was generated by the solar pannels?")
print("\n answer to question no 1")
print("the total electricity was generated by the solar panels is=",total_Electricity_Exported(df),"kWh")

#Q2
print("\nQ2= how much electricity was consumed by the household ?")
print("\n answer to question no 2")
print("the net elctricity consumed by the housegold is ",net_consumption(df),"kWh")
print(consumption_rate(df))
#Q3
print("\nQ3= how the weather affect solar generaton ?")
print("\n answer to question no 3")
corr_temp, corr_cloud, corr_rain, corr_humidity=weather_impact_analysis(df)
print(" correlation with max temperature is =", round(corr_temp, 2))
print(" correlation with cloud cover is =", round(corr_cloud, 2))
print(" correlation with rainfall is =", round(corr_rain, 2))
print(" correlation with humidity is =", round(corr_humidity, 2))
print(" that means: Sunny days = More Generation, Cloudy  &  Rainy days = Less Generation")
factors = [
    (corr_temp, "Max Temperature"),
    (corr_cloud, "Cloud Cover"),
    (corr_rain, "Rainfall"),
    (corr_humidity, "Humidity")]
for corr, name in factors:
    (check_relation_strength(corr, name))

#Q4
print("\nQ4=which days were more efficient ?")
print("\n answer to question no 4")
print("the top 5 efficient days were-")
print(top5_efficient_days(df))

#Q5
print("\nQ5. Can future solar production be estimated ?")
print("\n answer to question no 5")
print("from the given data we can estimate the future of solar production")
print("the estimated solar generation is-")
print(avg_solar_generation(df),"kWh")
print("the estimated peak power is-")
print(average_Peak_Power(df))
print("the estimated max peak power is-")
print(max_peak_power(df))

#=====================================================================================================
#                                           TASK QUESTIONS
#=====================================================================================================

#T1
print("Task-1. determine the month with the highest solar production ?")
print("\n answer to task no 1 ")
print(highesst_production_month(df))

#t2
print("Task-2. analyze whether temperature affects solar generation ")
print("\n answer to task no 2 ")
print(temp_correlation(df))

#t3
print("Task-3.study the effect of cloud cover and rainfall")
print("\n answer to task no 3 ")
print(cloud_rainfall_correlation(df))

#t4
print("Task4. Estimate household savings due to solar energy")
print("\n answer to task no 4 ")
print("the household's net savings is-")
print("Rs",daily_savings(df).sum())

#t5
print("Task-5. Find the most efficient and least efficient day")
print("\n answer to task no 5 ")
print(efficient_and_not_efficient_days(df))

#t6
print("Task-6. determine whether solar production is sufficient for household needs")
print("\n answer to task no 6 ")
print(avg_self_sufficiency(df))

#======================================================================================================
#                                           GRAPHS/FIGURES
#======================================================================================================

#generaton trend
daily_generation(df)
plt.show()
plt.close()

#weather vs generation
cloud_vs_generation(df)
plt.show()
plt.close()

#saving analysis
daily_savings_graph(df)
plt.show()
plt.close()


#monthly consumption
monthly_consumption(df)
plt.show()
plt.close()

#efficiency distribution
df["Efficiency"]=(df["Solar_Generation_kWh"]/df["Electricity_Consumed_kWh"]) * 100
efficiency_graph(df)
plt.show()
plt.close()

#==============================================================================================
#                                               CHALLENGE
#==============================================================================================

print(solar_performance_index(df))
print("CHALLENEG DONE")